### Creating value along the full data life-cycle from idea, where you are now, to where the world needs you to go.

Your sponsorship enables DADEDA to keep following big questions and lend visualization power to critical research and innovations of others. Your funds will directly be invested in necessary technology tools or subscriptions to continue this work.

- Global visual insights to worldwide challenges like climate change 🗺️ 🌐 🌏 🌍 🌎 
- Affordable housing focused on homeownership strategies 🏘️ 🏡 🏚️ 🏠 
- Hugging trees through computer programming code 🌳 🌴 🌲 
- Add a feature request issue to any repository to suggest new directions



The work of Data Design Dimension is grounded in a firm belief that when data is a valued asset, with shared understanding and accountability, and appropriate translation and skepticism, you can visualize meaningful progress and see the next opportunity today.

**Thank you for considering supporting Data Design Dimension!**

